name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - uses: ZenithalHourlyRate/nix-shell-action@v4
        with:
          interpreter: bash
          script: bazel build //...
      - uses: ZenithalHourlyRate/nix-shell-action@v4
        with:
          interpreter: bash
          script: bazel test //...
